version: "3"
services:
  apache:
    image: gaoliveira21/php72-apache
    container_name: codeigniter_app
    volumes:
      - ./default.conf:/etc/apache2/sites-available/default.conf
      - .:/var/www/html/app
    ports:
      - "8080:80"
      - "443:443"
  mysql:
    image: mysql
    container_name: mysql_db
    volumes:
      - ./data/mysql:/var/www/html/app/data/mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
